### ISSUE TITLE
Better way to get the schedule

### ISSUE THREAD

**Issue by Esinko** [OpenWilma/openwilma.js#19]
The schedule of any Wilma user can be requested from "/schedule/export/students/\<id>/?date=<date, ie. 08.10.2020>" as plain JSON instead of parsing it out with the page. If the query is left out periods will be returned. The \<id>is the student id. The request is made as a GET request.

**Comment by developerfromjokela** [comment]
Does it work without the ID?

**Comment by Esinko** [comment]
Yeah it does not. Github formatted the URL incorrectly at first. I had to escape the tags to fix that. Anyhow, I'll address this in the next profiles update. As we first need a way to get the logged in users id.

**Comment by developerfromjokela** [comment]
One way is via overview

**Comment by developerfromjokela** [comment]
Exactly said, the formkey

**Comment by developerfromjokela** [comment]
Or fetch the schedule HTML page and get the URL there

**Comment by Esinko** [comment]
Nah I'll just do the profiles update first and then this.
