### ISSUE TITLE
schedule not working due to undefined variable data

### ISSUE THREAD

**Issue by Nikedi** [OpenWilma/openwilma.js#25]
In the file parser.js function toRoom() fails to work if a room is not assigned in a schedule "slot".
This happens because in the function `async schedule(data)` the following snippet assumes HuoneInfo has some data in it.
`rooms: this.toRoom(entry.HuoneInfo["0"]["0"])`
`
    toRoom(data){
        return {
            id: data.kortti,
            shortName: data.lyhenne,
            name: data.nimi
        }
    }
`
Especially now as we are in distance learning most classes dont actually have classrooms assigned to them.

**Comment by developerfromjokela** [comment]
In our parsing guide we encourage to always check if item exists before proceeding to parse, often Visma's JSON is not reliable and items just disappear and re-appear randomly.

But thanks anyways, we'll try to fix that.

**Comment by Esinko** [comment]
Thanks for the issue, I'll get on fixing that as soon as possible. Please note that the current version of OpenWilma in the main branch is going to be deprecated soon, when the 1.0 version catches up to it. 1.0 will provide much better usability and stability.

**Comment by Esinko** [comment]
@Nikedi Your issue has been resolved. If you encounter any further problems regarding the patch, please don't hesitate to leave a message in this issue about it. If you encounter any other problems or have any more off-topic questions about OpenWilma, please make a new issue as usual.

**Comment by Nikedi** [comment]
The problem was that `data` was undefined and thus data.kortti returns an error and thus checking for `data.kortti == undefined` doesnt return `true`.
Instead it should check for `data == undefined`

**Comment by Esinko** [comment]
Ah. That should be fixed now. Thanks for the clarification 👍 
Please verify that the issue was fixed so I can close this issue.

**Comment by Nikedi** [comment]
Looks like it's working now.

**Comment by Esinko** [comment]
Perfect! I'll close this issue then.
